main: me.thecamzone.CamsLootTables
name: CamsLootTables
version: 2.0.0
description: Provides custom loot tables for generated structures.
api-version: 1.19
author: TheCamZone
depend: [ItemsAdder, EcoEnchants, NBTAPI]

commands:
  loottable:
    description: Main command for administrators
    aliases: [lt, loottables]
    permission: camsloottables.admin
    permission-message: "Unknown command. Type \"/help\" for help."
    usage: /<command>